<?xml version="1.0"?>
<!DOCTYPE Doc[
<!ELEMENT Doc ( Customer* , Payment* , Order+ , Search+ , Bank*)>
<!ELEMENT Customer (first_name , last_name , email , phone_number , address)>
<!ELEMENT Payment ( amount+ , type* )>
<!ELEMENT Order (name+ , order_type* , number*)>
<!ELEMENT Search ( resturant_search+ , food_search+)>
<!ELEMENT Bank ( bank_Name* , account_Number* , account_Name* , account_Type*)>
<!ATTLIST Customer id CDATA #REQUIRED>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone_number (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT amount (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT order_type (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT resturant_search (#PCDATA)>
<!ELEMENT food_search (#PCDATA)>
<!ELEMENT bank_Name (#PCDATA)>
<!ELEMENT account_Number (#PCDATA)>
<!ELEMENT account_Name (#PCDATA)>
<!ELEMENT account_Type (#PCDATA)>

]>


<Doc>



<Customer id = '22323'>
<first_name>Philip  </first_name>
<last_name> Tairov </last_name>
<email> tariovp@gmail.com </email>
<phone_number> 089433435 </phone_number>
<address> 1 spagethi mafia  </address>
</Customer>

<Payment>
<amount> 100 </amount>
<type> Apple Pay </type>
</Payment>

<Payment>
<amount> 12.95</amount>
<type> Cash </type>
</Payment>

<Payment>
<amount> 43.65 </amount>
<type> card </type>
</Payment>





<Order>
<name> Chicken Nuggets </name>
<order_type> Takeaway</order_type>
<number> 203992123 </number>
</Order>

<Search>
<resturant_search> Mad eggs </resturant_search>
<food_search> Beef Burger  </food_search>
</Search>


<Bank> 
<bank_Name> Allied Irish Banks </bank_Name>
<account_Number> 20331234
</account_Number>
<account_Name> Folabi 
</account_Name>
<account_Type> Student account </account_Type>
</Bank>

</Doc>
