<?xml version="1.0" ?>

<!DOCTYPE Just_Eat [
<!ELEMENT Just_Eat (Search*)>
<!ELEMENT Search (name+, email, phone, dateofbirth)>
<!ATTLIST Search restaurant_search CDATA #REQUIRED>
<!ATTLIST Search food_search CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
]>

<Just_Eat>
	<Search restaurant_search = 'Mad Egg' food_search = 'Beef Burger'>
    		<name> Abdel Azuzzy </name>
    		<email> elrayah@hotmail.com </email>
    		<phone> "089334252 </phone>
		<dateofbirth> 9/01/2000 </dateofbirth>
  	</Search>
	<Search restaurant_search = 'Burger King' food_search = 'Triple Cheesy Whopper'>
    		<name> Ben Dover </name>
    		<email> bdove@gmail.com </email>
    		<phone> 0872637478 </phone>
		<dateofbirth> 27/09/1998 </dateofbirth>
  	</Search>
	<Search restaurant_search = 'Dominos Pizza' food_search = 'Mighty Meaty'>
    		<name> John Kennedy </name>
    		<email> jken@gmail.com </email>
    		<phone> 0856974751 </phone>
		<dateofbirth> 06/03/1991 </dateofbirth>
  	</Search>
</Just_Eat>






