<?xml version="1.0"?>
<!DOCTYPE doc[
<!ELEMENT doc ( settings, Just_eat )>
<!ELEMENT settings ( firstname*, lastname*, emailaddress?, password?, phonenumber*, address)>
<!ELEMENT Just_eat ( settings.User_Name, settings.User_Email, settings.User_Phone)>
<!ATTLIST doc number CDATA #REQUIRED>
<!ELEMENT settings.User_Name (#PCDATA)>
<!ELEMENT settings.User_Email (#PCDATA)>
<!ELEMENT settings.User_Phone (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT emailaddress (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT phonenumber (#PCDATA)>
<!ELEMENT address (#PCDATA)>


]>


<doc number = "2">

<settings>
 <firstname> Matt </firstname>
    <lastname> Murdock </lastname>
    <emailaddress> mattie@tcd.ie </emailaddress>
    <password> ******** </password>
    <phonenumber>0874532242</phonenumber>
    <address> 69 White Manor </address>
    </settings>
  <Just_eat>
<settings.User_Name> Abdel</settings.User_Name>
<settings.User_Email> abdel232@gmail.com </settings.User_Email>
<settings.User_Phone> 0834355532</settings.User_Phone>
  </Just_eat>
  

</doc>


